### ISSUE TITLE
Material editor/resource manager memory leak

### ISSUE THREAD

**Issue by JunaMeinhold** [HexaEngine/HexaEngine#80]
### Reproduction:
Edit a material or hit the generate button.

### Log:

>00:05 [Error] ******LIVE INSTANCE: Texture2D: MaterialTextureResourceFactory, Line:44 
[HexaEngine.D3D11.D3D11Texture2D,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11Texture2D..ctor(ComPtr1 texture, Texture2DDescription description)
   at HexaEngine.D3D11.D3DScratchImage.CreateTexture2D(IGraphicsDevice device, Usage usage, BindFlags bindFlags, CpuAccessFlags accessFlags, ResourceMiscFlag miscFlag)
   at HexaEngine.D3D11.D3D11TextureLoader.LoadTexture2D(TextureFileDescription desc)
   at HexaEngine.Core.Graphics.Texture2D..ctor(IGraphicsDevice device, TextureFileDescription description, String filename, Int32 lineNumber)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE: 
[HexaEngine.D3D11.D3D11GraphicsPipeline,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.D3D11GraphicsPipeline..ctor(D3D11GraphicsDevice device, GraphicsPipelineDesc desc, String dbgName)
   at HexaEngine.D3D11.D3D11GraphicsDevice.CreateGraphicsPipeline(GraphicsPipelineDesc desc, String filename, Int32 line)
   at HexaEngine.Core.Graphics.IGraphicsDevice.CreateGraphicsPipelineState(GraphicsPipelineDesc pipelineDesc, GraphicsPipelineStateDesc desc, String filename, Int32 line)
   at HexaEngine.Resources.MaterialShaderPass..ctor(String name, IGraphicsDevice device, GraphicsPipelineDesc pipelineDesc, GraphicsPipelineStateDesc desc)
   at HexaEngine.Resources.MaterialShader.Compile()
   at HexaEngine.Resources.MaterialShader.Reload()
   at HexaEngine.Resources.Factories.MaterialShaderResourceFactoryExtensions.UpdateMaterialShader(ResourceManager manager, MaterialShader shader, MaterialData desc)
   at HexaEngine.Resources.Factories.MaterialResourceFactoryExtensions.UpdateMaterial[T](ResourceManager manager, MaterialData desc)
   at HexaEngine.Editor.MaterialEditor.MaterialEditorWindow.UpdateMaterialTaskVoid()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE: Texture2D: MaterialTextureResourceFactory, Line:44 
[HexaEngine.D3D11.D3D11Texture2D,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11Texture2D..ctor(ComPtr1 texture, Texture2DDescription description)
   at HexaEngine.D3D11.D3DScratchImage.CreateTexture2D(IGraphicsDevice device, Usage usage, BindFlags bindFlags, CpuAccessFlags accessFlags, ResourceMiscFlag miscFlag)
   at HexaEngine.D3D11.D3D11TextureLoader.LoadTexture2D(TextureFileDescription desc)
   at HexaEngine.Core.Graphics.Texture2D..ctor(IGraphicsDevice device, TextureFileDescription description, String filename, Int32 lineNumber)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE:  
[HexaEngine.D3D11.D3D11SamplerState,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11SamplerState..ctor(ComPtr1 sampler, SamplerStateDescription description)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE: Texture2D: MaterialTextureResourceFactory, Line:44.SRV 
[HexaEngine.D3D11.D3D11ShaderResourceView,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11ShaderResourceView..ctor(ComPtr1 srv, ShaderResourceViewDescription description)
   at HexaEngine.Core.Graphics.Texture2D..ctor(IGraphicsDevice device, TextureFileDescription description, String filename, Int32 lineNumber)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE: VertexBuffer: MeshLODData, Line:604 
[HexaEngine.D3D11.D3D11Buffer,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11Buffer..ctor(ComPtr1 buffer, BufferDescription desc)
   at HexaEngine.Core.Graphics.Buffers.VertexBuffer1..ctor(IGraphicsDevice device, T* vertices, UInt32 count, CpuAccessFlags flags, String filename, Int32 lineNumber)
   at HexaEngine.Core.IO.Binary.Meshes.MeshLODData.CreateVertexBuffer(IGraphicsDevice device, CpuAccessFlags accessFlags)
   at HexaEngine.Resources.Mesh..ctor(IResourceFactory factory, ResourceGuid id, IGraphicsDevice device, MeshDesc desc)
   at HexaEngine.Resources.Factories.MeshResourceFactory.CreateInstance(ResourceManager manager, ResourceGuid name, MeshDesc desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MeshResourceFactoryExtensions.LoadMesh(ResourceManager manager, MeshDesc desc)
   at HexaEngine.Resources.Factories.MeshResourceFactoryExtensions.<>c__DisplayClass3_0.<LoadMeshAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE:  
[HexaEngine.D3D11.D3D11SamplerState,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11SamplerState..ctor(ComPtr1 sampler, SamplerStateDescription description)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE: IndexBuffer: MeshLODData, Line:564 
[HexaEngine.D3D11.D3D11Buffer,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11Buffer..ctor(ComPtr1 buffer, BufferDescription desc)
   at HexaEngine.Core.Graphics.Buffers.IndexBuffer1..ctor(IGraphicsDevice device, T[] indices, CpuAccessFlags flags, String filename, Int32 lineNumber)
   at HexaEngine.Core.IO.Binary.Meshes.MeshLODData.CreateIndexBuffer(IGraphicsDevice device, CpuAccessFlags accessFlags)
   at HexaEngine.Resources.Mesh..ctor(IResourceFactory factory, ResourceGuid id, IGraphicsDevice device, MeshDesc desc)
   at HexaEngine.Resources.Factories.MeshResourceFactory.CreateInstance(ResourceManager manager, ResourceGuid name, MeshDesc desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MeshResourceFactoryExtensions.LoadMesh(ResourceManager manager, MeshDesc desc)
   at HexaEngine.Resources.Factories.MeshResourceFactoryExtensions.<>c__DisplayClass3_0.<LoadMeshAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE: Texture2D: MaterialTextureResourceFactory, Line:44.SRV 
[HexaEngine.D3D11.D3D11ShaderResourceView,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11ShaderResourceView..ctor(ComPtr1 srv, ShaderResourceViewDescription description)
   at HexaEngine.Core.Graphics.Texture2D..ctor(IGraphicsDevice device, TextureFileDescription description, String filename, Int32 lineNumber)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE:  
[HexaEngine.D3D11.D3D11SamplerState,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11SamplerState..ctor(ComPtr1 sampler, SamplerStateDescription description)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE: Texture2D: MaterialTextureResourceFactory, Line:44.SRV 
[HexaEngine.D3D11.D3D11ShaderResourceView,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11ShaderResourceView..ctor(ComPtr1 srv, ShaderResourceViewDescription description)
   at HexaEngine.Core.Graphics.Texture2D..ctor(IGraphicsDevice device, TextureFileDescription description, String filename, Int32 lineNumber)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE:  
[HexaEngine.D3D11.D3D11SamplerState,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11SamplerState..ctor(ComPtr1 sampler, SamplerStateDescription description)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE: Texture2D: MaterialTextureResourceFactory, Line:44.SRV 
[HexaEngine.D3D11.D3D11ShaderResourceView,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11ShaderResourceView..ctor(ComPtr1 srv, ShaderResourceViewDescription description)
   at HexaEngine.Core.Graphics.Texture2D..ctor(IGraphicsDevice device, TextureFileDescription description, String filename, Int32 lineNumber)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE: Texture2D: MaterialTextureResourceFactory, Line:44.SRV 
[HexaEngine.D3D11.D3D11ShaderResourceView,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11ShaderResourceView..ctor(ComPtr1 srv, ShaderResourceViewDescription description)
   at HexaEngine.Core.Graphics.Texture2D..ctor(IGraphicsDevice device, TextureFileDescription description, String filename, Int32 lineNumber)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE:  
[HexaEngine.D3D11.D3D11SamplerState,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11SamplerState..ctor(ComPtr1 sampler, SamplerStateDescription description)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE: Texture2D: MaterialTextureResourceFactory, Line:44 
[HexaEngine.D3D11.D3D11Texture2D,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11Texture2D..ctor(ComPtr1 texture, Texture2DDescription description)
   at HexaEngine.D3D11.D3DScratchImage.CreateTexture2D(IGraphicsDevice device, Usage usage, BindFlags bindFlags, CpuAccessFlags accessFlags, ResourceMiscFlag miscFlag)
   at HexaEngine.D3D11.D3D11TextureLoader.LoadTexture2D(TextureFileDescription desc)
   at HexaEngine.Core.Graphics.Texture2D..ctor(IGraphicsDevice device, TextureFileDescription description, String filename, Int32 lineNumber)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE: Texture2D: MaterialTextureResourceFactory, Line:44 
[HexaEngine.D3D11.D3D11Texture2D,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11Texture2D..ctor(ComPtr1 texture, Texture2DDescription description)
   at HexaEngine.D3D11.D3DScratchImage.CreateTexture2D(IGraphicsDevice device, Usage usage, BindFlags bindFlags, CpuAccessFlags accessFlags, ResourceMiscFlag miscFlag)
   at HexaEngine.D3D11.D3D11TextureLoader.LoadTexture2D(TextureFileDescription desc)
   at HexaEngine.Core.Graphics.Texture2D..ctor(IGraphicsDevice device, TextureFileDescription description, String filename, Int32 lineNumber)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]
00:05 [Error] ******LIVE INSTANCE: Texture2D: MaterialTextureResourceFactory, Line:44 
[HexaEngine.D3D11.D3D11Texture2D,    at HexaEngine.D3D11.DisposableBase..ctor()
   at HexaEngine.D3D11.DeviceChildBase..ctor()
   at HexaEngine.D3D11.D3D11Texture2D..ctor(ComPtr1 texture, Texture2DDescription description)
   at HexaEngine.D3D11.D3DScratchImage.CreateTexture2D(IGraphicsDevice device, Usage usage, BindFlags bindFlags, CpuAccessFlags accessFlags, ResourceMiscFlag miscFlag)
   at HexaEngine.D3D11.D3D11TextureLoader.LoadTexture2D(TextureFileDescription desc)
   at HexaEngine.Core.Graphics.Texture2D..ctor(IGraphicsDevice device, TextureFileDescription description, String filename, Int32 lineNumber)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactory.LoadInstance(ResourceManager manager, MaterialTexture instance, MaterialTexture desc)
   at HexaEngine.Resources.ResourceFactory2.GetOrCreateInstance(ResourceGuid id, TData instanceData)
   at HexaEngine.Resources.ResourceManager.CreateInstance[T,TData](ResourceGuid id, TData data)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.LoadTexture(ResourceManager manager, MaterialTexture desc)
   at HexaEngine.Resources.Factories.MaterialTextureResourceFactoryExtensions.<>c__DisplayClass2_0.<LoadTextureAsync>b__0()
   at System.Threading.Tasks.Task1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
]

**Comment by JunaMeinhold** [comment]
Stale issue, closing.
